CREATE TABLE WEkend_events (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    time  TIME NOT NULL,
    place TEXT,
    details TEXT,
    date_published TIMESTAMPTZ DEFAULT now() NOT NULL
);